services:
  # Postgres local instance
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Config
  config:
    build: ../config
#    image: ghcr.io/filberol/highload_systems/config:latest
    platform: linux/amd64
    container_name: config
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    networks:
      - app-network

  # Department
  department:
    build: ../department
#    image: ghcr.io/filberol/highload_systems/department:latest
    platform: linux/amd64
    container_name: department
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - config
      - eureka
      - kafka1
      - kafka2
      - kafka3
    environment:
      DEPARTMENT_DB_URL: r2dbc:postgresql://postgres:5432/postgres
      DEPARTMENT_DB_USERNAME: postgres
      DEPARTMENT_DB_PASSWORD: postgres
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  # Auth
  auth:
#    image: ghcr.io/filberol/highload_systems/auth:latest
    platform: linux/amd64
    build: ../auth
    container_name: auth
    ports:
      - "8085:8085"
    depends_on:
      - config
      - postgres
      - eureka
    environment:
      AUTH_DB_URL: jdbc:postgresql://postgres:5432/postgres
      AUTH_DB_USERNAME: postgres
      AUTH_DB_PASSWORD: postgres
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  notification:
    build: ../notification
    container_name: notification
    platform: linux/amd64
    ports:
      - "8091:8091"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - eureka
    environment:
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  # Eureka
  eureka:
    build: ../eureka
#    image: ghcr.io/filberol/highload_systems/eureka:latest
    platform: linux/amd64
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka
    depends_on:
      - config
  # Gateway
  gateway:
    build: ../gateway
#    image: ghcr.io/filberol/highload_systems/gateway:latest
    platform: linux/amd64
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - config
      - eureka
    environment:
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  file:
    build: ../files
#    image: ghcr.io/filberol/highload_systems/files:latest
    platform: linux/amd64
    container_name: file
    ports:
      - "8090:8090"
    depends_on:
      - config
      - minio
      - postgres
    environment:
      FILE_DB_URL: r2dbc:postgresql://postgres:5432/postgres
      FILE_DB_USERNAME: postgres
      FILE_DB_PASSWORD: postgres
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_BUCKET: oxygen-bucket
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  # Eureka
  order:
    build: ../order
#    image: ghcr.io/filberol/highload_systems/order:latest
    platform: linux/amd64
    container_name: order
    ports:
      - "8087:8087"
    depends_on:
      - config
      - postgres
      - eureka
    environment:
      ORDER_DB_URL: jdbc:postgresql://postgres:5432/postgres
      ORDER_DB_USERNAME: postgres
      ORDER_DB_PASSWORD: postgres
      EUREKA_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  # Oxygen
  oxygen:
    build: ../oxygen
#    image: ghcr.io/filberol/highload_systems/oxygen:latest
    platform: linux/amd64
    container_name: oxygen
    ports:
      - "8096:8096"
    depends_on:
      - config
      - postgres
      - eureka
    environment:
      OXYGEN_DB_URL: jdbc:postgresql://postgres:5432/postgres
      OXYGEN_DB_USERNAME: postgres
      OXYGEN_DB_PASSWORD: postgres
      OXYGEN_CLIENT_URL: http://eureka:8761/eureka
    networks:
      - app-network
  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
    platform: linux/amd64
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_SERVICE_PUBLIC_ENDPOINT: http://localhost:9000
    networks:
      - app-network
    volumes:
      - minio-data:/data
  kafka1:
    image: apache/kafka:latest
    ports:
      - 29092:29092
      - 9092:9092
    hostname: kafka1
    platform: linux/amd64
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092, CONTROLLER://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS:  1@kafka1:19092, 2@kafka2:19092, 3@kafka3:19092
    volumes:
      - kafka1-data:/var/lib/kafka/data
    networks:
      - app-network
  kafka2:
    image: apache/kafka:latest
    ports:
      - 29093:29092
      - 9093:9092
    hostname: kafka2
    platform: linux/amd64
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENERS: PLAINTEXT://:29093,PLAINTEXT_HOST://:9093, CONTROLLER://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS:  1@kafka1:19092, 2@kafka2:19092, 3@kafka3:19092
    volumes:
      - kafka2-data:/var/lib/kafka/data
    networks:
      - app-network
  kafka3:
    image: apache/kafka:latest
    ports:
      - 29094:29092
      - 9094:9092
    hostname: kafka3
    platform: linux/amd64
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENERS: PLAINTEXT://:29094,PLAINTEXT_HOST://:9094, CONTROLLER://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092, 2@kafka2:19092, 3@kafka3:19092
    volumes:
      - kafka3-data:/var/lib/kafka/data
    networks:
      - app-network
#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    ports:
#      - 8090:8080
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:29092,kafka2:29093,kafka3:29094
#    links:
#      - kafka1
#      - kafka2
#      - kafka3

volumes:
  minio-data:
  kafka1-data:
  kafka2-data:
  kafka3-data:

networks:
  app-network:
    driver: bridge
