server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anekoss/configs.git
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka