spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/}${POSTGRES_DB:oxygen}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/}${POSTGRES_DB:oxygen}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jackson:
    property-naming-strategy: SNAKE_CASE

feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000