CREATE TABLE IF NOT EXISTS order_room
(
    id UUID DEFAULT uuid() PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES room,
    order_id UUID NOT NULL REFERENCES orders,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    left_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);