server:
  port: ${CONFIG_SERVICE_PORT:8088}

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
  security:
    user:
      name: ${CONFIG_SERVICE_USER:user}
      password: ${CONFIG_SERVICE_PASS:pass}