name: department build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/department.yml
      - department/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/department

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Build and Test
        run:  gradle :department:build -x test

  build-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    name: Build Docker Image
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./department
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
