name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image and run tests
        run: |
          docker build -t filberol/highload-test:latest --target builder .
      - name: Archive JaCoCo coverage report
        run: |
          id=$(docker create filberol/highload-test:latest)
          docker cp $id:/build/jacoco/test.exec ./test.exec
          docker rm -v $id
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: ./test.exec