name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t filberol/highload-test:latest --target builder .
      - name: Run tests
        run: |
          docker run --rm -v ./jacoco:/src/build/jacoco filberol/highload-test:latest gradle jacocoTestReport
      - name: Archive JaCoCo coverage report
        run: |
          mkdir -p coverage
          cp -r jacoco/ coverage/
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: coverage