name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image and run tests
        run: |
          docker build -t filberol/highload-test:latest --target builder .
      - name: Archive JaCoCo coverage report
        run: |
          docker create --name highload-test filberol/highload-test:latest
          docker cp highload-test:/app/build/jacoco/test.exec ./test.exec
          docker rm -v highload-test
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: ./test.exec